### ISSUE TITLE
About LearnedTrajandIDEncoding

### ISSUE THREAD

**Issue by rashidch** [vita-epfl/social-transmotion#4]
Hi, 

thank you for your awesome research project. 

Can you please provide an explanation for why Trajectory and Person ID encoding are used together?

Why do you add **learned encoding** to `(0 to 128), x[:, :, :, 0:half*2:2]` and **person encoding** to `(1 to 128), x[:, :, :, 1:half*2:2]`

![image](https://github.com/vita-epfl/social-transmotion/assets/8865579/b9b0cf40-db82-4d67-b3fe-97c9fde5f669)

**Comment by yanggao2000** [comment]
Hi @rashidch 

Thanks for your interest!

As you mentioned we used one encoder for both trajectory information and person ID. Since trajectory data and person ID are relatively compact data compared with other visual cues (e.g., pose keypoints), encoding them together is more efficient than encoding independently with two different modules. 

Hope this brief explanation helps you understand!

**Comment by rashidch** [comment]
Hi @yanggao2000 

Can you also release code and prepared data for ETH/UCY dataset and Pedestrians and Cyclists in Road Traffic dataset?

**Comment by yanggao2000** [comment]
Hi @rashidch 

It is quite redundant for us to prepare similar code for the datasets used in the appendix material. Please refer to our code for preparing the JTA dataset (https://drive.google.com/drive/folders/1iIp2B5y85OKZ7DkW7gBkmulUxMWW5SkY), as we used the same method to prepare both datasets as you requested.

**Comment by yanggao2000** [comment]
Hi @rashidch

Unfortunately, we currently don't have plans to release the processed data for those datasets. However, one can obtain them by referring to our code for preparing the JTA dataset (https://drive.google.com/drive/folders/1iIp2B5y85OKZ7DkW7gBkmulUxMWW5SkY) and adjusting it, as we used the same method to prepare those data.
