### ISSUE TITLE
length of input (9) and output (12)

### ISSUE THREAD

**Issue by WangZhuping123** [vita-epfl/social-transmotion#9]
If I want to change the trajectory length of input (9) and output (12), what should I modify? Do I need to regenerate the preprocessed dataset?

**Comment by yanggao2000** [comment]
Hi, thanks for your question. 
Yes, you should regenerate the preprocessed data since the observation and prediction horizons are fixed. About the preprocessing, you can refer to this [issue](https://github.com/vita-epfl/social-transmotion/issues/2) thread. After regenerating the data, you need to modify the dataloading process so that the model handles specific input/output frame lengths as you want.
